### ISSUE TITLE
current issues  

### ISSUE THREAD

**Issue by Priyanka328** [dfki-ric/xrock_gui_model#13]
- [ ] if the subcomponent configuration is empty by clicking on "config components", the configuration window will be not opened. (workaround: click on "config nodes" first, then on "config components")

**Comment by Priyanka328** [comment]
We have now a types field in the componentModelWidget to add the types . @annaborn  can you please test?

**Comment by m0rsch1** [comment]
This one is old and can be closed? @Priyanka328

**Comment by Priyanka328** [comment]
yes. I am closing it
