### ISSUE TITLE
Edges that are defined in ComponentModels in a confronting direction are not shown

### ISSUE THREAD

**Issue by hwiedPro** [dfki-ric/xrock_gui_model#16]
I have two Interfaces an Outgoing and and an Incoming, when I create the edge between those from Outgoing to Incoming, X-Rock-Gui is not able to display this edge.

@m0rsch1 This is a correct way of defining an edge between Interfaces, isn't it?

**Comment by m0rsch1** [comment]
@hwiedPro This is the intended way of defining a connection: from output via connected_to edge to input. This is to encode the direction of information flow. I becomes more obvious if we have bidirectional interfaces where the edge direction encodes who is sending info and who receives it (or both).

However, the issue you are describing here is none of the xrock_gui_model. It is an issue of the Tool (Deimos) you are using to connect things. It does not check if the connection attempt was successful or not. Instead it just updates the DB. The xrock_gui is correctly showing the missing edge which is NOT present in the DB.
